# Generated by Django 6.0 on 2025-12-13 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheduling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує"),
                            ("in_progress", "У процесі"),
                            ("completed", "Завершено"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "subjects",
                    models.JSONField(
                        help_text='Список предметів: [{"name": "Математика"}, ...]'
                    ),
                ),
                (
                    "groups",
                    models.JSONField(
                        help_text='Групи з предметами: [{"name": "ІП-21", "subjects": [{"subject": "Математика", "lectures": 2, "practices": 2}]}]'
                    ),
                ),
                (
                    "teachers",
                    models.JSONField(
                        help_text='Викладачі: [{"name": "Іванов І.І.", "subjects": [{"subject": "Математика", "is_lecturer": true, "is_practitioner": true}]}]'
                    ),
                ),
                (
                    "classrooms",
                    models.JSONField(help_text='Аудиторії: [{"name": "101"}, ...]'),
                ),
                (
                    "duration_weeks",
                    models.IntegerField(help_text="Тривалість навчання у тижнях"),
                ),
                (
                    "max_daily_slots",
                    models.IntegerField(help_text="Максимальна кількість пар на день"),
                ),
                (
                    "desired_days_count",
                    models.IntegerField(
                        help_text="Бажана кількість навчальних днів (1-7)"
                    ),
                ),
                (
                    "checkpoint_generation",
                    models.IntegerField(
                        default=0, help_text="Номер останнього обробленого покоління"
                    ),
                ),
                (
                    "checkpoint_population",
                    models.JSONField(
                        blank=True, help_text="Популяція на момент чекпоїнту", null=True
                    ),
                ),
                (
                    "checkpoint_best_fitness",
                    models.FloatField(
                        blank=True,
                        help_text="Найкраща оцінка на момент чекпоїнту",
                        null=True,
                    ),
                ),
                (
                    "best_schedules",
                    models.JSONField(
                        blank=True, help_text="Найкращі знайдені розклади", null=True
                    ),
                ),
                (
                    "problems",
                    models.JSONField(
                        blank=True, help_text="Список проблем у розкладі", null=True
                    ),
                ),
                (
                    "suggestions",
                    models.JSONField(blank=True, help_text="Список порад", null=True),
                ),
                (
                    "final_fitness",
                    models.FloatField(
                        blank=True, help_text="Фінальна оцінка", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedulings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Розклад",
                "verbose_name_plural": "Розклади",
                "ordering": ["-created_at"],
            },
        ),
    ]
