# Generated by Django 6.0 on 2025-12-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduling",
            name="problems",
        ),
        migrations.RemoveField(
            model_name="scheduling",
            name="suggestions",
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="best_schedules",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="checkpoint_best_fitness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="checkpoint_generation",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="checkpoint_population",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="classrooms",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="desired_days_count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="duration_weeks",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="final_fitness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="groups",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="max_daily_slots",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує"),
                    ("in_progress", "У процесі"),
                    ("completed", "Завершено"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="subjects",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="scheduling",
            name="teachers",
            field=models.JSONField(),
        ),
    ]
